name: Smoke

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install yarn
        run: npm install --global yarn
      - name: Install packages
        run: yarn
      - name: Setup
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Artifact - coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: packages/tests/coverage
      - name: Build
        run: yarn build-all
      - name: Artifact - examples build
        uses: actions/upload-artifact@v2
        with:
          name: examples-build
          path: packages/examples/build
      - name: Hot
        run: yarn check-hot
